### ISSUE TITLE
[Question] [ws-sbom-generator] How to run the ws-sbom-generator task after ws scan task during CI

### ISSUE THREAD

**Issue by adubey8** [whitesource-ps/ws-sbom-generator#80]
**Question**  
Can you provide a yaml example for running a `wss-unified-agent.jar` agent for scanning an artifact and then run sbom generator to get all the dependencies. I am trying it as below, but I have two questions following this approach:
1. How to obtain the project token from wss-unified-agent scan to be further used by another command task to run the ws_sbom_generator?
2. How to obtain the WhiteSource SPDX Report from the task, is below task correct?

```
      # Download and run the unified agent
      - task: CmdLine@2
        displayName: Download the latest Unified Agent
        inputs:
          script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
      
      - task: CmdLine@2
        displayName: Run Unified Agent Scan
        inputs:
          script: 'java -jar wss-unified-agent.jar -c ./secure-supply-chain/wss.config -apiKey $(WHITE_SOURCE_API_KEY) -product STIC-cloud -project stic-security-sbom-01'
      
      - task: CmdLine@2
        displayName: Generate WhiteSource SPDX Report
        inputs:
          script: |
            export WS_URL=https://app-eu.whitesourcesoftware.com
            export WS_PROJECTTOKEN=VALUE
            echo WS_PROJECTTOKEN: $WS_PROJECTTOKEN
            export WS_URL=$WS_URL
            export USERKEY=VALUE
            echo USERKEY: $USERKEY
            export WS_ORG_TOKEN=VALUE
            echo === Installing WhiteSource SBOM Generator ===
            pip3 install ws_sbom_generator
            echo === Generating SBOM ===
            python3 -m ws_sbom_generator.sbom_generator -u $USERKEY -k $WS_ORG_TOKEN -s $WS_PROJECTTOKEN -a $WS_URL -t json -o ./whitesource-spdx

      - task: CmdLine@2
        displayName: Publish WhiteSource SPDX Report
        uses: actions/upload-artifact@master
        with:
            name: WhiteSource SPDX report
            path: ${{github.workspace}}/whitesource-spdx

      - publish: $(System.DefaultWorkingDirectory)/whitesource
        artifact: whitesource_scan_report   
```

**Environment Details**  
 - OS: Ubuntu 18.04
 - Version 
  - ws-sbom-generator  0.4.1
  - ws-sdk             0.9.0.5
  - ws-spdx-tools      0.7.0a3.post2
